board: ls1028a: Add an empty video hw init function
The video driver causes a link failure when config VIDEO built-in,

drivers/video/cfb_console.c:2022: undefined reference to `video_hw_init'

Adding an empty video hw init to slove the build issue, now the board
does not support display anything on U-boot.

Signed-off-by: Wen He <wen.he_1@nxp.com>